
// Register locations // 

#define CR 		(MPC5XXX_PSC1+MPC5XXX_PSC_CR)
#define SICR 	(MPC5XXX_PSC1+MPC5XXX_PSC_SICR)
#define MCLK 	(MPC5XXX_CDM+MPC5XXX_CDM_PSC1_MCLK_EN)
#define CLKEN 	(MPC5XXX_CDM+MPC5XXX_CDM_CLKEN)
#define CCR 	(MPC5XXX_PSC1+MPC5XXX_PSC_CCR)		// Set delays
#define CTUR 	(MPC5XXX_PSC1+MPC5XXX_PSC_CTUR)	// more delays
#define CTLR 	(MPC5XXX_PSC1+MPC5XXX_PSC_CTLR)	// more delays
#define RFALARM (MPC5XXX_PSC1+MPC5XXX_PSC_RFALARM)
#define TXALARM (MPC5XXX_PSC1+MPC5XXX_PSC_TFALARM)


